baseURL = 'https://bagofwordsai.github.io/'
title = 'Bag of Words'
theme = "paper"

author = "bagofwordsai"
copyright = "Copyright © 2008–2019, Steve Francia and the lee.so; all rights reserved."
pagination = 3
languageCode = "tr"
DefaultContentLanguage = "tr"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

[languages]
  [tr]
    contentDir = "content/turkish"
    languageName = "Türkçe"
    weight = 10
  [en]
    contentDir = "content/english"
    languageName = "English"
    weight = 20

[params]
# Socials
  twitter = 'bagofwordsai'
  github = 'BagofWordsai'
  # instagram = 'nan.xiaobei'
# Home Page Profile
  avatar = 'https://bagofwordsai.github.io/bow_logo.png'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
  name = 'Bag of Words'
  bio = 'Türkçe NLP Topluluğu'


# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "Hakkımızda"
    url = "/turkish/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

